Description: >
  This CloudFormation template creates a private Application Load Balancer (ALB) in an existing VPC.
  The ALB is placed in private subnets and is not accessible from the Internet.
  The ALB is associated with a target group that contains the instances or IP addresses of backend servers.
  The ALB listens on port 80 and forwards requests to the target group.
  A health check is configured to check the health of the backend servers every 30 seconds.

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: The ID of the VPC where the ALB will be deployed.
  PrivateSubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: The IDs of the private subnets where the ALB will be deployed.
  ServiceName:
    Type: String
    Description: The name of the service that will use the ALB.

Resources:
  ALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Join ['', [!Ref ServiceName, '-alb']]
      Scheme: internal
      Type: application
      Subnets: !Ref PrivateSubnetIds
      Tags:
        - Key: Name
          Value: !Join ['', [!Ref ServiceName, '-alb']]

  ALBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref ALB
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroup

  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Join ['', [!Ref ServiceName, '-tg']]
      VpcId: !Ref VpcId
      Port: 80
      Protocol: HTTP
      HealthCheckIntervalSeconds: 30
      HealthCheckProtocol: HTTP
      HealthCheckPath: /health
      Matcher: { HttpCode: '200' }
      TargetType: ip
      Tags:
        - Key: Name
          Value: !Join ['', [!Ref ServiceName, '-tg']]

Outputs:
  AlbArn:
    Value: !Ref ALB
    Export:
      Name: !Join ['-', [!Ref 'AWS::StackName', 'AlbArn']]
