AWSTemplateFormatVersion: '2010-09-09'
Description: Create an Amazon EKS cluster without VPC configuration

Parameters:
  ClusterName:
    Type: String
    Description: The name of the Amazon EKS cluster.

  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: The VPC ID for the EKS cluster.

  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: The subnet IDs for the EKS cluster.

Resources:
  EKSCluster:
    Type: AWS::EKS::Cluster
    Properties:
      Name: !Ref ClusterName
      RoleArn: !GetAtt EKSClusterRole.Arn
      ResourcesVpcConfig:
        VpcId: !Ref VpcId
        SubnetIds: !Ref SubnetIds

  EKSClusterRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - eks.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
        - arn:aws:iam::aws:policy/AmazonEKSServicePolicy
