AWSTemplateFormatVersion: "2010-09-09"
Description: "Deploy a Windows Server 2019 instance with Fleet Manager access, without direct RDP exposure"

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: "Select the VPC for the instance"

  SubnetId:
    Type: AWS::EC2::Subnet::Id
    Description: "Select a subnet for the instance"
  InstanceName:
    Type: String
    Description: "Name of the instance"
Resources:
  # Security Group allowing ONLY SSM access (No direct RDP)
  WindowsSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Security Group for Windows instance allowing Fleet Manager access only"
      VpcId: !Ref VpcId

  # Windows Instance
  WindowsInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: "t3.medium"
      ImageId: !Sub "{{resolve:ssm:/aws/service/ami-windows-latest/Windows_Server-2019-English-Full-Base}}"
      SubnetId: !Ref SubnetId
      SecurityGroupIds:
        - !Ref WindowsSecurityGroup
      IamInstanceProfile: !Ref SSMInstanceProfile
      Tags:
        - Key: Name
          Value: !Ref InstanceName
  # IAM Role for SSM Access
  SSMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
      Path: "/"

  # Instance Profile for SSM
  SSMInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref SSMRole

Outputs:
  InstanceId:
    Description: "ID of the Windows instance"
    Value: !Ref WindowsInstance
  InstancePublicDNS:
    Description: "Public DNS of the Windows instance"
    Value: !GetAtt WindowsInstance.PublicDnsName
