AWSTemplateFormatVersion: '2010-09-09'
Description: Route 53 Resolver outbound endpoint + forwarding rule using 3 AZs

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC to associate the resolver rule with
  SubnetIdA:
    Type: AWS::EC2::Subnet::Id
    Description: Subnet in AZ1 for the outbound endpoint ENI
  SubnetIdB:
    Type: AWS::EC2::Subnet::Id
    Description: Subnet in AZ2 for the outbound endpoint ENI
  SubnetIdC:
    Type: AWS::EC2::Subnet::Id
    Description: Subnet in AZ3 for the outbound endpoint ENI
  ForwardDomain:
    Type: String
    Description: Domain (suffix) or exact FQDN to forward
  RuleName:
    Type: String
    Description: Friendly name for the resolver rule (no dots)
    AllowedPattern: "(?!^[0-9]+$)([a-zA-Z0-9\\-_\\' ]+)"
    ConstraintDescription: "Use letters, numbers, spaces, hyphens, underscores or apostrophes; not all digits."
  TargetDnsIps:
    Type: CommaDelimitedList
    Default: 8.8.8.8,1.1.1.1
    Description: Public DNS resolvers to forward to (comma-separated)
  CreateIpv6Egress:
    Type: String
    AllowedValues: ["true","false"]
    Default: "false"
    Description: Add IPv6 egress rules if dual-stack

Conditions:
  UseIpv6: !Equals [!Ref CreateIpv6Egress, "true"]

Resources:
  OutboundEndpointSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SG for Route 53 Resolver outbound endpoint
      VpcId: !Ref VpcId
      SecurityGroupEgress:
        - IpProtocol: udp
          FromPort: 53
          ToPort: 53
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 53
          ToPort: 53
          CidrIp: 0.0.0.0/0
        - !If
          - UseIpv6
          - IpProtocol: udp
            FromPort: 53
            ToPort: 53
            CidrIpv6: ::/0
          - !Ref "AWS::NoValue"
        - !If
          - UseIpv6
          - IpProtocol: tcp
            FromPort: 53
            ToPort: 53
            CidrIpv6: ::/0
          - !Ref "AWS::NoValue"

  OutboundEndpoint:
    Type: AWS::Route53Resolver::ResolverEndpoint
    Properties:
      Name: out-public-dns
      Direction: OUTBOUND
      SecurityGroupIds:
        - !Ref OutboundEndpointSG
      IpAddresses:
        - SubnetId: !Ref SubnetIdA
        - SubnetId: !Ref SubnetIdB
        - SubnetId: !Ref SubnetIdC

  ForwardRule:
    Type: AWS::Route53Resolver::ResolverRule
    Properties:
      Name: !Ref RuleName
      DomainName: !Ref ForwardDomain
      RuleType: FORWARD
      ResolverEndpointId: !Ref OutboundEndpoint
      TargetIps:
        - Ip: !Select [0, !Ref TargetDnsIps]
          Port: 53
        - Ip: !Select [1, !Ref TargetDnsIps]
          Port: 53

  AssocToVpc:
    Type: AWS::Route53Resolver::ResolverRuleAssociation
    Properties:
      Name: !Sub assoc-${RuleName}
      ResolverRuleId: !Ref ForwardRule
      VPCId: !Ref VpcId

Outputs:
  OutboundEndpointId:
    Value: !Ref OutboundEndpoint
  ResolverRuleId:
    Value: !Ref ForwardRule
  OutboundSGId:
    Value: !Ref OutboundEndpointSG
